import {WebGLRenderer,Scene,PerspectiveCamera,Group,SphereGeometry,Mesh,MeshPhongMaterial,AmbientLight,DirectionalLight,CanvasTexture,BufferGeometry,Float32BufferAttribute,Points,PointsMaterial,Line,LineBasicMaterial,Vector3,QuadraticBezierCurve3,SRGBColorSpace} from 'three';
import {feature} from 'topojson-client';
import land from 'world-atlas/land-110m.json';
export function mountGlobe(host){
 let renderer;try{renderer=new WebGLRenderer({alpha:true,antialias:true,powerPreference:'low-power'});}catch{return;}
 renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.outputColorSpace=SRGBColorSpace;host.append(renderer.domElement);host.classList.add('globe-ready');
 const scene=new Scene(),camera=new PerspectiveCamera(34,1,.1,100);camera.position.z=7.8;
 const map=document.createElement('canvas');map.width=2048;map.height=1024;const ctx=map.getContext('2d');ctx.fillStyle='#083c56';ctx.fillRect(0,0,map.width,map.height);ctx.fillStyle='#5f9b9d';ctx.strokeStyle='#97c9c7';ctx.lineWidth=1;
 for(const item of feature(land,land.objects.land).features)for(const polygon of item.geometry.coordinates){ctx.beginPath();for(const ring of polygon){ring.forEach(([lon,lat],i)=>{const x=(lon+180)/360*map.width,y=(90-lat)/180*map.height;i?ctx.lineTo(x,y):ctx.moveTo(x,y);});ctx.closePath();}ctx.fill('evenodd');ctx.stroke();}
 const texture=new CanvasTexture(map);texture.colorSpace=SRGBColorSpace;
 const world=new Group();scene.add(world);const shell=new Mesh(new SphereGeometry(1.8,64,40),new MeshPhongMaterial({map:texture,shininess:12,specular:0x183f49}));world.add(shell);scene.add(new AmbientLight(0xffffff,1.8));const light=new DirectionalLight(0xffffff,1.6);light.position.set(-3,4,4);scene.add(light);
 const vector=(lat,lon,r=1.825)=>{const phi=(90-lat)*Math.PI/180,theta=(lon+180)*Math.PI/180;return new Vector3(-r*Math.sin(phi)*Math.cos(theta),r*Math.cos(phi),r*Math.sin(phi)*Math.sin(theta));};
 const points=[];for(let lat=-75;lat<=75;lat+=7)for(let lon=-180;lon<180;lon+=7){const v=vector(lat,lon);points.push(v.x,v.y,v.z);}const geo=new BufferGeometry();geo.setAttribute('position',new Float32BufferAttribute(points,3));world.add(new Points(geo,new PointsMaterial({color:0xb5d8da,size:.019,transparent:true,opacity:.36})));
 const lineMaterial=new LineBasicMaterial({color:0x8cd5de,transparent:true,opacity:.23});for(const lat of [-60,-30,0,30,60]){const pts=[];for(let lon=0;lon<=360;lon+=3)pts.push(vector(lat,lon));world.add(new Line(new BufferGeometry().setFromPoints(pts),lineMaterial));}
 const origin=vector(18,-77,1.85);const destinations=[[40,-74],[51,-.1],[35,139],[-12,-77],[25,55]];
 const beacons=[];for(const [lat,lon]of destinations){const end=vector(lat,lon,1.85);const mid=origin.clone().add(end).normalize().multiplyScalar(3.1);const curve=new QuadraticBezierCurve3(origin,mid,end);const routeGeo=new BufferGeometry().setFromPoints(curve.getPoints(80));world.add(new Line(routeGeo,new LineBasicMaterial({color:0xffce32,transparent:true,opacity:.85})));const beacon=new Mesh(new SphereGeometry(.037,10,8),new MeshPhongMaterial({color:0xffce32,emissive:0xffb722}));world.add(beacon);beacons.push({beacon,curve});}
 world.rotation.y=-1.2;world.rotation.z=.15;
 const reduce=matchMedia('(prefers-reduced-motion:reduce)');let visible=false,raf=0,previous=0,elapsed=0,targetX=0,targetY=-1.2;
 function size(){const box=host.getBoundingClientRect();renderer.setSize(box.width,box.height);camera.aspect=box.width/box.height;camera.updateProjectionMatrix();renderer.render(scene,camera);}
 const resize=new ResizeObserver(size);resize.observe(host);size();
 function draw(time){raf=0;if(!visible||document.hidden||reduce.matches)return;if(time-previous>33){elapsed+=Math.min((time-previous)/1000,.05);previous=time;world.rotation.y+=(targetY+Math.sin(elapsed*.12)*.18-world.rotation.y)*.04;world.rotation.x+=(targetX-world.rotation.x)*.04;beacons.forEach(({beacon,curve},i)=>beacon.position.copy(curve.getPoint((elapsed*.065+i*.17)%1)));renderer.render(scene,camera);host.dataset.draws=String(renderer.info.render.calls);}raf=requestAnimationFrame(draw);}
 function restart(){cancelAnimationFrame(raf);raf=0;previous=performance.now();if(reduce.matches){beacons.forEach(({beacon,curve},i)=>beacon.position.copy(curve.getPoint(.3+i*.1)));renderer.render(scene,camera);}else if(visible&&!document.hidden)raf=requestAnimationFrame(draw);}
 const observer=new IntersectionObserver(entries=>{visible=entries[0].isIntersecting;restart();});observer.observe(host);document.addEventListener('visibilitychange',restart);reduce.addEventListener('change',restart);
 host.addEventListener('pointermove',event=>{if(event.pointerType!=='mouse'||reduce.matches)return;const box=host.getBoundingClientRect();targetX=(event.clientY-box.top-box.height/2)/box.height*.25;targetY=-1.2+(event.clientX-box.left-box.width/2)/box.width*.5;});host.addEventListener('pointerleave',()=>{targetX=0;targetY=-1.2;});
 renderer.domElement.addEventListener('webglcontextlost',event=>{event.preventDefault();cancelAnimationFrame(raf);host.classList.remove('globe-ready');observer.disconnect();});
 window.addEventListener('pagehide',()=>{cancelAnimationFrame(raf);observer.disconnect();resize.disconnect();texture.dispose();renderer.dispose();scene.traverse(object=>{object.geometry?.dispose();if(object.material)for(const material of [].concat(object.material))material.dispose();});},{once:true});
}
